### ISSUE TITLE
[ISSUE] Terraform import panic on importing rudderstack source

### ISSUE THREAD

**Issue by annez** [rudderlabs/terraform-provider-rudderstack#6]
**Describe the issue**
Have attempted to start importing resources into tfstate (because currently the exported config will show that its going to create all the resources. On initial import of web source I get a panic on terraform import.

**To Reproduce**
Mention the steps to reproduce the behavior that causes the bug/issue:

1. Import your terraform config with the python script
2. Example of tf config:
```
resource "rudderstack_source" "web" {
  name = "Web"
  type = "Javascript"
  config = {
    object = {
    }
  }
}
```
2. Run `terraform import`

```
rudderstack_source.web: Importing from ID "1gEP09ki43fDmr8746t9UOEmRvM"...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-rudderstack_v0.2.10 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15f4017]

goroutine 32 [running]:
terraform-provider-rudderstack/rudderstack.resourceSource.ImportState(0x1, 0xc000139340, 0x18803e0, 0xc000047f00, 0xc000038b20, 0x1b, 0xc0001e2680)
	terraform-provider-rudderstack@/rudderstack/resource_source.go:290 +0x267
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).importResourceState(0xc00010c5a0, 0x18803e0, 0xc000047f00, 0xc000123460, 0xc0001f9a70)
	github.com/hashicorp/terraform-plugin-framework@v0.4.2/tfsdk/serve_import.go:99 +0x48d
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).ImportResourceState(0xc00010c5a0, 0x18803e0, 0xc000047f00, 0xc000123460, 0xc000047ec0, 0xc000110800, 0x188b9e0)
	github.com/hashicorp/terraform-plugin-framework@v0.4.2/tfsdk/serve_import.go:128 +0xb9
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ImportResourceState(0xc00050d760, 0x18803e0, 0xc000047ec0, 0xc0001a0a50, 0xc00050d760, 0xc0001fa660, 0xc0004c4b58)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov6/tf6server/server.go:348 +0xda
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ImportResourceState_Handler(0x174f600, 0xc00050d760, 0x18804a0, 0xc0001fa660, 0xc000110840, 0x0, 0x18804a0, 0xc0001fa660, 0xc000134140, 0x31)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:399 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000228e00, 0x1888fc0, 0xc000483980, 0xc0001dc200, 0xc00010c630, 0x1d07058, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x4fd
google.golang.org/grpc.(*Server).handleStream(0xc000228e00, 0x1888fc0, 0xc000483980, 0xc0001dc200, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd55
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001201a0, 0xc000228e00, 0x1888fc0, 0xc000483980, 0xc0001dc200)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x204

Error: The terraform-provider-rudderstack_v0.2.10 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**
Imports source successfully into tfstate

**Screenshots**
![image](https://user-images.githubusercontent.com/1567681/150636739-fa599c03-2dcd-429d-926d-63906335171c.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.1 Monterey

**Comment by nishantsharma** [comment]
Bug fixed and release made.
